apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-micro-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-micro-service
  template:
    metadata:
      labels:
        app: first-micro-service
    spec:
      containers:
        - image: hieronymusa/prvaslika:latest
          name: first-micro-service
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://ella.db.elephantsql.com:5432/cywnmvra
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-user-pass
                  key: username
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-user-pass
                  key: password
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: first-micro-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: first-micro-service
